apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app
  labels:
    app: vite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: shubhamshinde2025/ultimate-cicd:12
        ports:
        - containerPort: 5173
