apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-deployment
  namespace: vito
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite
  template:
    metadata:
      labels:
        app: vite
    spec:
      containers:
      - name: vite
        image: shubhamshinde2025/ultimate-cicd:12
        ports:
        - containerPort: 5173
