apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-deployment
  namespace: vito
  labels:
    app: vite
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vite
  template:
    metadata:
      labels:
        app: vite
    spec:
      containers:
      - name: vite
        image: shubhamshinde2025/ultimate-cicd:replaceImageTag
        ports:
        - containerPort: 5173
