apiVersion: v1
kind: Service
metadata:
  name: vite-svc
  namespace: vito
  app: vite
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: vite
  ports:
    - port: 5173
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5173
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
